name = "seo-analytics-dashboard"
pages_build_output_dir = "./dist"
compatibility_date = "2026-05-01"

[[d1_databases]]
binding = "DB"
database_name = "seo-analytics-db"
database_id = ""

[[durable_objects.bindings]]
name = "COUNTER"
class_name = "Counter"
